### PR TITLE
Add NFT page add Listing Actions

### PR DESCRIPTION
**Pull request by echohtp**
Adds the support to load a single NFT on the page via `?mint=` url query param

API Actions added:
 - List NFT
 - Delist NFT

listing-states

### CODE REVIEW

**Review by richardwu — APPROVED** [review]
So can you load a user's inventory + listed/non-listed NFTs now?

**Comment by richardwu** [comment]
Can you also make the buttons more uniform/same size?

**Comment by echohtp** [comment]
> So can you load a user's inventory + listed/non-listed NFTs now?

No there isnt a user inventory yet, this enables single view NFT page and linking to a nft/listing from an external source (my first thought is discord bot can link users to an active listing)

> Can you also make the buttons more uniform/same size?

Yup, will do

**Comment by echohtp** [comment]
Fixed buttons 
image

**Pull request merged**
